defaults: &defaults
  email:
    notifications_mail: 'notifications@domain.io'
    support_mail: 'support@doamin.io'
  test: 'notifications@domain.io'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults