defaults: &defaults
  email:
    notifications_mail: 'notifications@doter.mx'
    support_mail: 'support@doter.mx'
  test: 'notifications@mail.com'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults